<a href="https://colab.research.google.com/github/anujtech313/Tensorflow/blob/main/Tensorflow1_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


In [4]:
#Creating a scalar (rank 0 tensor)
scalar = tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [5]:
scalar. ndim

0

In [6]:
#creating a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[10., 7.],
                              [7., 10.],
                              [8. , 9.]], dtype = tf.float16) #specify datatype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
tensor = tf.constant([[[10,7,6],
                       [7, 10,8],
                       [5, 6, 7]],
                      [[3, 5, 6],
                      [4, 6, 7],
                       [5,7,8]],
                      [[4, 8, 9],
                      [2, 5 ,9],
                       [3, 6 ,4]]])
tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[10,  7,  6],
        [ 7, 10,  8],
        [ 5,  6,  7]],

       [[ 3,  5,  6],
        [ 4,  6,  7],
        [ 5,  7,  8]],

       [[ 4,  8,  9],
        [ 2,  5,  9],
        [ 3,  6,  4]]], dtype=int32)>

In [12]:
tensor.ndim

3

In [13]:
tensor.ndim

3

In [14]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([9, 4])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 4], dtype=int32)>)

In [15]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [16]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
#Creating random tensor

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1 , random_2 , random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [18]:
# Creating two random and different tensors

random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3,2))
random_4 = tf.random.Generator.from_seed(54)
random_4 = random_4.normal(shape=(3,2))

random_3 , random_4, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.01380118, -0.24827152],
        [ 1.2111493 , -0.7199124 ],
        [-0.04082382,  2.6791053 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [19]:
not_shuffled = tf.constant([[10, 5],
                            [5 , 6],
                            [4, 3]])
# Gets different results each time
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  5],
       [ 4,  3],
       [ 5,  6]], dtype=int32)>

In [20]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 4,  3],
       [ 5,  6],
       [10,  5]], dtype=int32)>

In [21]:
tf.random.set_seed(42)

tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  5],
       [ 5,  6],
       [ 4,  3]], dtype=int32)>

In [22]:
#other ways to make tensors

tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [23]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [24]:
#converting numpy arrays to tensors

import numpy as np
numpy_A= np.arange(1, 25, dtype = np.int32)

A = tf.constant(numpy_A, shape = [2 , 4, 3])

numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)



```
**Getting information from tensors that is shape, Rank, Axis or Dimension, size**




In [25]:
rank_6_tensor = tf.zeros([2 ,3 ,4 ,5])
rank_6_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [26]:
rank_6_tensor.shape, rank_6_tensor.ndim, tf.size(rank_6_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [30]:
print("Datatype of every element:", rank_6_tensor.dtype)
print("number of dimensions(rank)", rank_6_tensor.ndim)
print("Shape of tensor", rank_6_tensor.shape)
print("Elemts along axis 0 of tensor:", rank_6_tensor.shape[0])
print("Elements along last axis of tensor", rank_6_tensor.shape[-1])
print("Total number of elements(2*3*4*5)", tf.size(rank_6_tensor).numpy()) 
print("elements along axis 1", rank_6_tensor.shape[2])

Datatype of every element: <dtype: 'float32'>
number of dimensions(rank) 4
Shape of tensor (2, 3, 4, 5)
Elemts along axis 0 of tensor: 2
Elements along last axis of tensor 5
Total number of elements(2*3*4*5) 120
elements along axis 1 4


**Adding extra dimension**

In [32]:
rank_2_tensor=tf.constant([[10, 4],
                          [4,3]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [ 4,  3]], dtype=int32)>

In [28]:
rank_7_tensor = tf.constant([[3,4],
                            [4,6]])
rank_7_tensor[:, -1]


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [33]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  4],
        [ 4,  3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 4]],
 
        [[ 4],
         [ 3]]], dtype=int32)>)

In [34]:
tf.expand_dims(rank_2_tensor, axis= -1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 4]],

       [[ 4],
        [ 3]]], dtype=int32)>

In [36]:
tensor = tf.constant([[10, 4],[3,4]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [13, 14]], dtype=int32)>

In [37]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [ 3,  4]], dtype=int32)>

In [38]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  40],
       [ 30,  40]], dtype=int32)>

In [39]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -6],
       [-7, -6]], dtype=int32)>

In [40]:
print (tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  4]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[112,  56],
       [ 42,  28]], dtype=int32)>

In [42]:
x = tf.constant([[1,2],
                [2,3],
                [4,5]])

y = tf.constant([[2,3],
                [4,5],
                [5,6]])

x , y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3],
        [4, 5]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 3],
        [4, 5],
        [5, 6]], dtype=int32)>)

In [43]:
tf.matmul(x , y)

InvalidArgumentError: ignored

In [46]:
x @ tf.reshape(y, shape = (2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12, 13, 16],
       [19, 21, 26],
       [33, 37, 46]], dtype=int32)>